### ISSUE TITLE
Missing/extra spaces in facts section

### ISSUE THREAD

**Issue by kaprijela** [kaprijela/zobro2#10]
Broken formatting resulted in broken facts after autoscraping the ZOO website, if you have time, please fix and push to `dbfiles`. I'll be going through the files in batches of twenty.

- [x] agamaKocincinska - krkavecVelky
- [x] kulikPisecny - pandaCervena
- [x] paovceHrivnata - tamarinZlutoruky
- [x] tapirJihoamericky - zirafaSitovana

**Comment by berkas1** [comment]
Should be ok now

**Comment by kaprijela** [comment]
Awesome, thanks!
